name: Code Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Print debug information for troubleshooting
      - name: Debug Info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch Name: ${{ github.head_ref || github.ref_name }}"

      # Step 3: Run the custom action
      - name: Gemini Code Scanner
        uses: ./
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token
          repo_name: ${{ github.repository }}  # Dynamically fetch the repo name
          branch_name: ${{ github.head_ref || github.ref_name }}  # Correct branch name logic
