name: Code Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Gemini Code Scanner
        uses: ./
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} 

      - name: Add comment to PR
        uses: thollander/actions-comment-pull-request@v1  # Use the comment action
        with:
          message: ${{ steps.gemini-scanner.outputs.review }}  # Pass the review as the message
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}