name: Code Scan

on:
  pull_request:
    types: [opened, synchronize]

permissions: write-all
jobs:
  scan:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: Gemini Code Scanner
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
     