name: Code Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gemini Code Scanner
        uses: ./ 
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          repo_name: GDGCloudLahore/gemini-code-scanner
          branch_name: ${{ github.head_ref }}  # Pass the branch name