name: Code Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
 
      - uses: actions/checkout@v3

      - name: Gemini Code Scanner
        uses: ./
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          repo_name: ${{ github.repository }}  
          branch_name: ${{ github.head_ref || github.ref_name }} 
