name: Code Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3
 

      # Step 3: Run the custom action
      - name: Gemini Code Scanner
        uses: ./
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    
